output_worker.check:
  stage: test
  image: rust:$RUST_VERSION
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - output-worker/**/*
        - sentry-integration/**/*
        - Cargo.*
  variables:
    SQLX_OFFLINE: "true"
  services:
    - postgres:$PG_VERSION
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - pushd output-worker
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test
