[package]
name = "hook0-output-worker"
version = "0.2.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.63"
chrono = "0.4.22"
clap = { version = "3.2.19", features = ["derive", "env", "cargo", "wrap_help"] }
hex = "0.4.3"
hmac = "0.12.1"
itertools = "0.10.3"
log = "0.4.17"
reqwest = { version = "0.11.11", default-features = false, features = ["rustls-tls", "trust-dns"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.144"
serde_json = "1.0.85"
sha2 = "0.10.3"
sqlx = { version = "0.5.13", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "time", "json", "offline"] }
strum = { version = "0.24.1", features = ["derive"] }
tokio = { version = "1.20.1", features = ["rt-multi-thread", "macros", "time"] }
uuid = { version = "0.8.2", features = ["v4"] }
