[package]
name = "hook0-output-worker"
version = "0.2.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.45"
chrono = "0.4.19"
clap = "3.0.0-beta.5"
hex = "0.4.3"
hmac = "0.11.0"
itertools = "0.10.1"
log = "0.4.14"
reqwest = { version = "0.11.6", default-features = false, features = ["rustls-tls", "trust-dns"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.130"
serde_json = "1.0.69"
sha2 = "0.9.8"
sqlx = { version = "0.5.9", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "time", "json", "offline"] }
tokio = { version = "1.13.0", features = ["rt-multi-thread", "macros", "time"] }
uuid = "0.8.2"
