[package]
name = "output-worker"
version = "0.1.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.35"
async-std = { version = "1.8.0", features = ["attributes"] }
chrono = "0.4.19"
clap = "3.0.0-beta.2"
env_logger = "0.8.1"
log = "0.4.11"
reqwest = { version = "0.10.9", default-features = false, features = ["rustls-tls"] }
serde = "1.0.118"
serde_json = "1.0.60"
sqlx = { version = "0.4.1", default-features = false, features = ["runtime-async-std-rustls", "postgres", "macros", "uuid", "chrono", "time", "json"] }
uuid = "0.8.1"
