[package]
name = "hook0-output-worker"
version = "0.2.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
log = "0.4.14"
reqwest = { version = "0.10.10", default-features = false, features = ["rustls-tls"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.125"
serde_json = "1.0.64"
sqlx = { version = "0.4.2", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "time", "json", "offline"] }
tokio = { version = "0.2.25", features = ["rt-threaded", "macros", "time"] }
uuid = "0.8.2"
