frontend.build:
  stage: build
  rules:
    - changes:
        - frontend/**/*
  image: node:$NODE_VERSION
  script:
    - pushd frontend/
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - frontend/dist/
