frontend.build:
  stage: build
  only:
      changes:
        - frontend/**
  image: node:$NODE_VERSION
  script:
    - pushd frontend/
    - npm ci
    - npm run build
    - npm run lint
    - npm run test:ci
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - frontend/dist/
