frontend.build:
  stage: build
  dependencies: []
  rules:
    - changes:
        - frontend/**/*
  image: node:$NODE_VERSION
  script:
    - pushd frontend/
    - npm ci
    - npm run build
  artifacts:
    name: "$CI_BUILD_NAME"
    paths:
      - frontend/node_modules/
      - frontend/dist/

frontend.check:
  stage: test
  dependencies:
    - frontend.build
  rules:
    - changes:
        - frontend/**/*
  image: node:$NODE_VERSION
  script:
    - pushd frontend/
    - npm run check
    - npm run lint
