[package]
name = "sentry-integration"
version = "0.1.0"
authors = ["François-Guillaume Ribreau <github@fgribreau.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sentry = { version = "0.18.0", features = ["with_log", "with_env_logger"] }
env_logger = "0.7.1"
log = "0.4.8"
