[package]
name = "sentry-integration"
version = "0.1.0"
description = "Sentry-related methods"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
log = "0.4.14"
sentry = { version = "0.22.0", default-features = false, features = ["backtrace", "contexts", "panic", "reqwest", "rustls", "log", "debug-logs"] }
