[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
log = "0.4.14"
reqwest = { version = "0.11.9", default-features = false, features = ["rustls-tls", "trust-dns"] }
serde = "1.0.136"
serde_json = "1.0.79"
thiserror = "1.0.30"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["v4"] }
