[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.33", features = ["serde"] }
lazy-regex = "3.1.0"
log = "0.4.20"
reqwest = { version = "0.11.24", default-features = false, features = ["trust-dns", "json"] }
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
thiserror = "1.0.56"
url = "2.5.0"
uuid = { version = "1.7.0", features = ["serde", "v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
