[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
chrono = { version = "0.4.22", features = ["serde"] }
log = "0.4.17"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls", "trust-dns", "json"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
thiserror = "1.0.37"
url = "2.3.1"
uuid = { version = "1.2.1", features = ["serde", "v4"] }
