[package]
name = "hook0-client"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.24", features = ["serde"] }
lazy-regex = "2.5.0"
log = "0.4.17"
reqwest = { version = "0.11.18", default-features = false, features = ["trust-dns", "json"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
url = "2.3.1"
uuid = { version = "1.3.3", features = ["serde", "v4"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
