keycloak-theme.build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE != "schedule"
      changes:
        - keycloak-theme/**/*
        - mediakit/**/*
  image: node:$NODE_VERSION
  before_script:
    - apt update -y && apt install -y --no-install-recommends default-jdk maven
  script:
    - pushd keycloak-theme/
    - npm ci
    - cp -v ../mediakit/logo/512x512.png ./src/main/resources/theme/hook0-redesign/email/img/logo.png
    - cp -v ../mediakit/logo/512x512.png ./src/main/resources/theme/hook0-redesign/login/resources/img/logo.png
    - cp -v ../mediakit/logo/favicon.ico ./src/main/resources/theme/hook0-redesign/login/resources/img/
    - npm run build
    - mvn package
  artifacts:
    paths:
      - keycloak-theme/target/hook0*.jar
