keycloak-theme.check:
  stage: build
  image: rust:$RUST_VERSION
  only:
    changes:
      - keycloak-theme/**/*
  before_script:
  script:
    - ACCESS_TOKEN=$(curl -s -q $ENDPOINT_IAM/auth/realms/hook0/protocol/openid-connect/token -d "grant_type=password&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET&username=$ACCOUNT_EMAIL&password=$ACCOUNT_PASSWORD" | jq -r .access_token)
    - curl -v --location --request PUT "${ENDPOINT_API}/deployments/${DEPLOYMENT_ID}/extensions/jars/4c2caa9e-ee4b-4494-8834-f1b25e9ea147" --header "Authorization: Bearer ${ACCESS_TOKEN}" --form 'extension=@hook0-redesign-2.0.6-SNAPSHOT.jar' --http1.1
