website.build:
  stage: build
  only:
      changes:
        - website/**
  image: node:$NODE_VERSION
  script:
    - pushd website/
    - npm ci
    - npm run build
  cache:
      key: ${CI_COMMIT_REF_SLUG}
      policy: push
      paths:
        - .npm
        - website/node_modules/
        - website/.parcel-cache/
  artifacts:
      paths:
        - website/dist

website.release:
  stage: release
  before_script:
    # https://github.com/netlify/cli/issues/1870
    - npm i -g --unsafe-perm netlify-cli
  script:
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir=dist/
  environment:
      name: production-website
      url: https://www.hook0.com
  needs:
    - job: website.build
      artifacts: true
  only:
    - master
  except:
    - schedules
  tags:
    - deploy
