api.check:
  stage: test
  image: rust:$RUST_VERSION
  rules:
    - changes:
        - api/**/*
        - sentry-integration/**/*
        - clients/rust/**/*
        - Cargo.*
  variables:
    SQLX_OFFLINE: "true"
  services:
    - postgres:$PG_VERSION
  before_script:
    - rustc --version && cargo --version
    - rustup component add clippy
    - rustup component add rustfmt
  script:
    - pushd api
    - cargo fmt --all -- --check
    - cargo clippy --all-targets --all-features -- -D warnings
    - cargo test

api.documentation:
  stage: documentation
  environment:
    name: production-api
    url: https://app.hook0.com/api/v1
  rules:
    - changes:
        - api/**
        - Cargo.*
  image: node:$NODE_VERSION
  script:
    - npx --yes rdme@8.3.0 openapi --id=${README_IO_ID} --key=${README_IO_KEY} --update https://app.hook0.com/api/v1/swagger.json
