[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6.0-beta.8"
actix-files = "0.6.0-beta.15"
actix-governor = { git = "https://github.com/AaronErhardt/actix-governor", rev = "df75c6dd88b1f4642ea7128f747bef52c465a28f", features = ["log"] }
actix-web = "4.0.0-beta.21"
actix-web-middleware-keycloak-auth = { git = "https://github.com/dsferruzza/actix-web-middleware-keycloak-auth", rev = "9c4f56cccc59138929ec3a1306d67e9f43f5bfe7", features = ["paperclip_compat"] }
anyhow = "1.0.53"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.10", features = ["derive", "env", "cargo", "wrap_help"] }
futures-util = "0.3.17"
http-api-problem = { version = "0.51.0", features = ["actix-web"] }
ipnetwork = "0.17.0"
lazy_static = "1.4.0"
log = "0.4.14"
paperclip = { git = "https://github.com/sfisol/paperclip", rev = "99db92949e95287fbeb8f3ea844291f1810cccee", features = ["actix", "chrono", "uuid"] }
rand = { version = "0.8.4", features = ["log"] }
regex = "1.5.4"
reqwest = { version = "0.11.9", default-features = false, features = ["rustls-tls", "trust-dns"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.134"
serde_json = "1.0.75"
strum = { version = "0.23.0", features = ["derive"] }
sqlx = { version = "0.5.10", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "offline", "migrate"] } # runtime-tokio-rustls because https://github.com/launchbadge/sqlx/issues/894#issuecomment-747821912
thiserror = "1.0.30"
url = "2.2.2"
uuid = { version = "0.8.2", features = ["serde"] }
validator = { version = "0.14.0", features = ["derive", "unic"] }
