[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2018"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0-beta.8"
actix-web = "4.0.0-beta.10"
actix-web-middleware-keycloak-auth = { version = "0.4.0-beta.2", features = ["paperclip_compat"] }
anyhow = "1.0.45"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.5"
futures-util = "0.3.17"
http-api-problem = { version = "0.51.0", features = ["actix-web"] }
ipnetwork = "0.17.0"
lazy_static = "1.4.0"
log = "0.4.14"
paperclip = { git = "https://github.com/sfisol/paperclip", rev = "41eea14e1d9c0a25107353a8eedcb26c09c7224e", features = ["actix", "chrono", "uuid"] }
regex = "1.5.4"
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.130"
serde_json = "1.0.69"
strum = { version = "0.22.0", features = ["derive"] }
sqlx = { version = "0.5.9", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "offline", "migrate"] } # runtime-tokio-rustls because https://github.com/launchbadge/sqlx/issues/894#issuecomment-747821912
uuid = { version = "0.8.2", features = ["serde"] }
