[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2018"
license = "SSPL-1.0"
license-file = "LICENSE.txt"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.5.0"
actix-web = "3.3.2"
actix-web-middleware-keycloak-auth = { git = "https://github.com/dsferruzza/actix-web-middleware-keycloak-auth", rev = "c9f53fe9ea110782256512d8595ba971cc964e66" }
anyhow = "1.0.42"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "3.0.0-beta.2"
http-api-problem = { version = "0.50.2", features = ["actix-web"] }
ipnetwork = "0.17.0"
lazy_static = "1.4.0"
log = "0.4.14"
paperclip = { git = "https://github.com/wafflespeanut/paperclip", rev = "20ec2e954dfb15613807130105a41e8f4b91066e", features = ["actix", "chrono", "uuid"] }
regex = "1.4.5"
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.125"
serde_json = "1.0.64"
strum = { version = "0.21.0", features = ["derive"] }
sqlx = { version = "0.4.2", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "offline"] } # runtime-tokio-rustls because https://github.com/launchbadge/sqlx/issues/894#issuecomment-747821912
uuid = { version = "0.8.2", features = ["serde"] }
