[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-cors = "0.6.4"
actix-files = "0.6.2"
actix-governor = { version = "0.4.0-beta.1", features = ["log"] }
actix-web = "4.2.1"
actix-web-middleware-keycloak-auth = { version = "0.4.0", features = ["paperclip_compat"] }
anyhow = "1.0.66"
async-recursion = "1.0.0"
base64 = "0.13.1"
chrono = { version = "0.4.22", features = ["serde"] }
clap = { version = "4.0.18", features = ["derive", "env", "cargo", "wrap_help"] }
futures-util = "0.3.25"
governor = "0.4.2"
hook0-client = { path = "../clients/rust" }
http-api-problem = { version = "0.55.0", features = ["actix-web"] }
ipnetwork = "0.19.0"
lazy_static = "1.4.0"
log = "0.4.17"
nom = "7.1.1"
nom-regex = "0.2.0"
paperclip = { git = "https://github.com/paperclip-rs/paperclip", rev = "aac5bc734a470f46c31b727b859cf9089f22c0be", default-features = false, features = ["actix4", "v3", "chrono", "uuid"] }
rand = { version = "0.8.5", features = ["log"] }
regex = "1.6.0"
reqwest = { version = "0.11.12", default-features = false, features = ["rustls-tls", "trust-dns"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.147"
serde_json = "1.0.87"
sqlx = { version = "0.6.2", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "offline", "migrate"] } # runtime-tokio-rustls because https://github.com/launchbadge/sqlx/issues/894#issuecomment-747821912
strum = { version = "0.24.1", features = ["derive"] }
thiserror = "1.0.37"
url = "2.3.1"
uuid = { version = "1.2.1", features = ["serde", "v4"] }
validator = { version = "0.16.0", features = ["derive", "unic"] }
