[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]

[dependencies]
actix = "0.13.1"
actix-cors = "0.6.5"
actix-files = "0.6.2"
actix-governor = { version = "0.5.0", features = ["log"] }
actix-web = "4.4.0"
actix-web-middleware-keycloak-auth = { version = "0.4.2", features = ["paperclip_compat"] }
anyhow = "1.0.75"
async-recursion = "1.0.5"
base64 = "0.21.5"
chrono = { version = "0.4.31", features = ["serde"] }
clap = { version = "4.4.11", features = ["derive", "env", "cargo", "wrap_help"] }
futures-util = "0.3.29"
governor = "0.6.0"
hook0-client = { path = "../clients/rust" }
http-api-problem = { version = "0.57.0", features = ["actix-web"] }
ipnetwork = "0.20.0"
lazy_static = "1.4.0"
log = "0.4.20"
nom = "7.1.3"
nom-regex = "0.2.0"
paperclip = { version = "0.8.2", default-features = false, features = ["actix4", "v3", "chrono", "uuid"] }
regex = "1.10.2"
reqwest = { version = "0.11.22", default-features = false, features = ["trust-dns"] }
sentry-actix = "0.32.0"
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.193"
serde_json = "1.0.108"
sqlx = { version = "0.7.3", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "migrate"] }
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.50"
url = "2.5.0"
uuid = { version = "1.6.1", features = ["serde", "v4"] }
validator = { version = "0.16.1", features = ["derive", "unic"] }

[features]
default = ["reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots", "hook0-client/reqwest-rustls-tls-webpki-roots"]
reqwest-rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots", "hook0-client/reqwest-rustls-tls-native-roots"]
