[package]
name = "hook0-api"
version = "0.1.0"
description = "Core API of Hook0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>", "François-Guillaume Ribreau <hook0@fgribreau.com>"]
edition = "2021"
license = "SSPL-1.0"
keywords = ["webhooks", "webhook", "webhook server", "events"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.0-beta.10"
actix-governor = { git = "https://github.com/AaronErhardt/actix-governor", rev = "5dec6a4d8837d1f30dfb2d209b76d0c463cac6e1" }
actix-web = "4.0.0-beta.14"
actix-web-middleware-keycloak-auth = { git = "https://github.com/dsferruzza/actix-web-middleware-keycloak-auth", rev = "a19991c17579e2bef268ac5ffedb8abff863eb22", features = ["paperclip_compat"] }
actix-cors = "0.6.0-beta.6"
anyhow = "1.0.51"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = { version = "3.0.0-rc.4", features = ["derive", "env", "cargo", "wrap_help"] }
futures-util = "0.3.18"
http-api-problem = { version = "0.51.0", features = ["actix-web"] }
ipnetwork = "0.17.0"
lazy_static = "1.4.0"
log = "0.4.14"
paperclip = { git = "https://github.com/sfisol/paperclip", rev = "418832f042adcd6939f6eb19115edcdd5543d47a", features = ["actix", "chrono", "uuid"] }
regex = "1.5.4"
reqwest = { version = "0.11.7", default-features = false, features = ["rustls-tls", "trust-dns"] }
sentry-integration = { path = "../sentry-integration" }
serde = "1.0.131"
serde_json = "1.0.72"
strum = { version = "0.23.0", features = ["derive"] }
sqlx = { version = "0.5.9", default-features = false, features = ["runtime-tokio-rustls", "postgres", "macros", "uuid", "chrono", "json", "ipnetwork", "offline", "migrate"] } # runtime-tokio-rustls because https://github.com/launchbadge/sqlx/issues/894#issuecomment-747821912
uuid = { version = "0.8.2", features = ["serde"] }
rand = { version = "0.8.4", features = ["log"] }
url = "2.2.2"
validator = { version = "0.14.0", features = ["derive", "unic"] }
